# go2rtc Configuration Example with Recording Settings

streams:
  camera1: rtsp://admin:password@192.168.1.100/stream1
  camera2: rtsp://admin:password@192.168.1.101/stream1
  doorbell: rtsp://admin:password@192.168.1.102/stream1

# Recording Configuration
recording:
  # Storage Settings
  base_path: "/var/recordings"                    # Base directory for all recordings
  path_template: "{year}/{month}/{day}/{stream}" # Directory structure template
  filename_template: "{stream}_{timestamp}"      # Filename template (without extension)
  default_format: "mp4"                         # Default output format
  create_directories: true                       # Auto-create directory structure

  # Automatic Segmentation Settings
  enable_segments: false                         # Enable automatic file segmentation
  segment_duration: "1h"                       # Duration before starting new file (1 hour)
  max_file_size: 2048                          # Max file size in MB before new file (2GB)

  # Retention Policy
  retention_days: 14                            # Keep recordings for 14 days
  retention_hours: 0                           # Alternative to retention_days (0 = use days)
  max_recordings: 50                           # Maximum recordings per stream
  max_total_size: 51200                        # Maximum total storage in MB (50GB)

  # Automatic Cleanup
  enable_cleanup: true                          # Enable automatic cleanup
  cleanup_interval: "2h"                       # Run cleanup every 2 hours
  move_to_archive: false                       # Delete old files instead of archiving
  archive_path: "/var/recordings/archive"      # Archive directory (if move_to_archive: true)

  # Recording Behavior
  auto_start: false                            # Don't auto-start recording when stream available
  restart_on_error: true                      # Restart recording if FFmpeg process fails
  buffer_time: "0s"                           # Pre-recording buffer duration
  post_recording_time: "10s"                  # Continue recording 10s after stream ends

  # Default Quality Settings
  default_video: "copy"                        # Copy video codec by default (no transcoding)
  default_audio: "copy"                        # Copy audio codec by default (no transcoding)
  bitrate_limit: ""                           # No bitrate limit by default

  # Monitoring and Metrics
  enable_metrics: false                        # Disable recording metrics
  metrics_interval: "5m"                      # Collect metrics every 5 minutes

  # Per-Stream Configuration - Specify which cameras to record
  streams:
    # Camera 1 - Always record with high quality
    camera1:
      enabled: true                            # Enable recording for this stream
      auto_start: true                         # Auto-start when stream becomes available
      video: "copy"                           # Copy video codec (no transcoding)
      audio: "copy"                           # Copy audio codec
      format: "mp4"                           # Output format
      enable_segments: true                    # Enable segmentation for this stream
      segment_duration: "2h"                  # 2-hour segments
      retention_days: 30                      # Keep for 30 days
      path_template: "security/{year}/{month}/{stream}"        # Custom path
      filename_template: "security_{stream}_{timestamp}"       # Custom filename
      
    # Camera 2 - Record but with different settings
    camera2:
      enabled: true
      auto_start: true
      video: "h264"                           # Transcode to H264 for compatibility
      audio: "aac"                            # Transcode to AAC
      bitrate_limit: "2M"                     # Limit to 2 Mbps
      format: "mkv"                           # Use MKV format
      retention_days: 7                       # Keep for 7 days only
      max_recordings: 20                      # Max 20 recordings for this camera
      
    # Doorbell - Motion-triggered recording only
    doorbell:
      enabled: true
      auto_start: false                       # Don't auto-start continuous recording
      record_on_motion: true                  # Record only on motion (future feature)
      video: "copy"
      audio: "copy"
      format: "mp4"
      retention_days: 60                      # Keep doorbell recordings longer
      path_template: "doorbell/{year}/{month}/{day}"
      filename_template: "doorbell_{timestamp}"
      
    # Camera 3 - Disabled (won't record even if global auto_start is true)
    camera3:
      enabled: false                          # Explicitly disable recording
      
    # Camera 4 - Custom quality settings
    camera4:
      enabled: true
      auto_start: true
      video: "h265"                           # Use H265 for better compression
      audio: "opus"                           # Use Opus for audio
      width: 1920                             # Force 1080p resolution
      height: 1080
      framerate: 15                           # Reduce to 15fps to save space
      enable_segments: true
      segment_duration: "30m"                 # 30-minute segments
      max_file_size: 512                      # Max 512MB per file
      retention_days: 14

# Example production configuration for high-volume surveillance
# recording:
#   base_path: "/mnt/surveillance"
#   path_template: "{year}/{month}/{day}/{hour}/{stream}"
#   filename_template: "{stream}_{date}_{time}"
#   default_format: "mkv"                     # Better for long recordings
#   
#   enable_segments: true                     # Split into hourly segments
#   segment_duration: "1h"
#   max_file_size: 1024                      # 1GB max per file
#   
#   retention_days: 30                       # Keep for 30 days
#   max_total_size: 512000                   # 500GB total limit
#   
#   enable_cleanup: true
#   cleanup_interval: "30m"                  # Check every 30 minutes
#   move_to_archive: true                    # Archive instead of delete
#   archive_path: "/mnt/archive"
#   
#   auto_start: true                         # Auto-record all streams
#   restart_on_error: true
#   
#   default_video: "h264"                    # Transcode to H264 for compatibility
#   default_audio: "aac"                     # Transcode to AAC
#   bitrate_limit: "2M"                      # Limit to 2 Mbps

# WebRTC and API configuration (existing)
webrtc:
  listen: ":8555"

api:
  listen: ":1984"